version: '3'

networks: 
    laravel:

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: yodawy-news-backend-nginx
        ports: 
            - "8080:80"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
        networks: 
            - laravel
    
    php:
        build: 
            context: .
        container_name: yodawy-news-backend-php
        volumes: 
            - ./src:/var/www/html
        command: "bash -c 'composer install --ignore-platform-reqs && php-fpm'"
        ports: 
            - "9000:9000"
        networks: 
            - laravel